### ISSUE TITLE
qliksense preflight <Create roles, rolebindings>

### ISSUE THREAD

**Issue by ffoysal** [qlik-oss/qliksense-k8s#123]
verify the cli has permission to do that

- `qliksense preflight createRole` 
- `qliksense preflight createRoleBinding`
- `qliksense preflight createServiceAccount`
- `qliksense preflight createRB` // it combines all three together

**Comment by ashwathishiva** [comment]
latest PR: https://github.com/qlik-oss/sense-installer/pull/276

**Comment by ashwathishiva** [comment]
PR: https://github.com/qlik-oss/sense-installer/pull/280
